#import "style.typ": project
#show: project

*Generation of mutation-corrected autologous midbrain dopaminergic progenitor cells for the treatment of familial Parkinson’s disease*

\

_Background_

Parkinson’s disease is a progressive neurodegenerative disease characterized by the loss of dopaminergic neurons from the substantia nigra, resulting in debilitating motor and non-motor symptoms. Current standard-of-care therapies include dopamine replacement and deep brain stimulation. While these can provide symptomatic relief, they do not affect the underlying disease progression; moreover, their efficacy wanes over time, and patients often develop complications such as motor fluctuations and dyskinesias. There remains an urgent need for disease-modifying interventions that slow, halt, or even reverse the loss of dopaminergic neurons — especially as the prevalence of Parkinson’s disease rises.

Cell replacement therapy is one such approach. The relatively precisely defined anatomical and cellular pathology of Parkinson’s allows a clear target for restoration, in contrast to other diseases with more diffuse neurodegeneration. Early trials used allogeneic human embryonic stem cells (hESCs) to generate surgically transplanted cell products that can engraft, mature, and functionally integrate to replace lost cells, as do many current clinical trials. An alternative is the autologous (i.e., patient-derived) approach, capitalizing on Shinya Yamanaka’s groundbreaking discovery that human somatic cells can be reprogrammed into ESC-like induced pluripotent stem cells (hiPSCs) #text(fill: red)[[Yamanaka]] — this includes my own lab’s ongoing clinical trial using autologously derived midbrain dopaminergic precursor (mDAP) cells. Beyond evading ethical concerns associated with hESCs, hiPSCs carry several advantages. They can be reliably generated and extensively tested for safety and efficacy. Furthermore, as autologous grafts are derived from the patient, they avoid the immunosuppression and prolonged prophylactic antibiotic use required with allogeneic grafts, a source of significant risk.

Yet no trial to date has specifically addressed the risk that transplanted cells will be lost to the same underlying degenerative process. Recent estimates suggest as many as 15-20% of Parkinson’s patients have an inherited or genetic form of the disease, and this number is likely to rise as our understanding of the genetic drivers of Parkinson’s disease improves #text(fill: red)[[Kolicheski]]. Familial Parkinson’s patients typically not only face an earlier age-of-onset, but more severe symptoms and disease progression as well. However, the application of current cell replacement approaches to these patients is complicated: in the case of hESC-derived therapies, the earlier age-of-onset means a longer risk window for immuno-rejection; in the case of hiPSC-derived therapies, the retention of pathogenic gene variants increases the risk that patient-derived transplanted tissue will succumb to the same cellular dysfunction.

\

_Proposed work_

To address this limitation, the proposed research integrates precise gene editing into the cell replacement paradigm. By correcting disease-causing mutations in patient-derived cells prior to differentiation and transplantation, this work aims to generate a graft that is both immunologically compatible and resistant to the underlying disease process.

This is made feasible by recent advances in gene editing technologies. The precedent of the safe, clinically effective application of _ex vivo_ gene editing (via CRISPR/Cas9--based programs) in autologous cell therapies was established by two trials, Casgevy (Vertex Pharmaceuticals) and BEAM-101 (Beam Therapeutics), in sickle cell disease #text(fill: red)[[Vertex, Beam]]. However, first-generation gene editing technologies such as CRISPR/Cas9 have several limitations, most critically the introduction of double-strand breaks, insertion-deletions, and other off-target effects. Prime editing is a next-generation gene editing technology that employs a Cas9 nickase fused to an engineered reverse transcriptase in complex with a prime editing guide RNA, enabling precise edits into cellular genomes without the need for double-strand breaks or exogenous donor DNA templates #text(fill: red)[[David Liu]]. Initial clinical data from the first prime editing therapeutic trial in p47phox chronic granulomatous disease demonstrate a correction rate of 82% in colony-forming cells, less than 2% unintended edits, a favorable safety profile and efficacious restoration of cellular function #text(fill: red)[[NCT06559176]]. The work proposed here would extend the paradigm of _ex vivo_ gene editing in autologous cell therapy to the central nervous system. 

Building on this foundation, gene editing and cellular reprogramming can be combined in a novel "one-step" strategy to simultaneously generate mutation-corrected hiPSCs from patient fibroblasts. Rather than sequentially gene editing and then reprogramming fibroblasts (or vice versa) --- a time-consuming series of steps that subjects cells to considerable stressors and risks increased genomic damage --- this approach integrates both steps simultaneously. Preliminary data from our lab demonstrate the successful generation of mutation-corrected hiPSC clones using this approach, with subsequent differentiation into mDAPs. 

Corrected cells will undergo extensive quality control testing to ensure safety and efficacy and suitability for clinical application _in vitro_ and _in vivo_. Functional testing will be used to demonstrate the correction of established Parkinson's disease--associated and mutation-specific cellular phenotypes following gene editing _in vitro_. The efficacy of corrected cell--derived grafts will be assessed via behavioral testing in 6-hydroxydopamine (6-OHDA) hemi-lesioned athymic rats, a well-established model of Parkinson's disease used to assess cell transplantation; administration of 6-OHDA to the medial forebrain bundle causes ipsilateral dopaminergic neuron loss resulting in motor function impairments. Safety will be assessed in immunocompromised Nod Scid $gamma$ mice implanted with patient-derived mutation-corrected mDAP grafts via histological and immunohistochemical analysis for evidence unexpected tumor formation, graft maturity, and the spread of graft cells beyond the immediate area of the graft, at 3 and 6 months post-transplantation.

This is a highly translational project that unifies regenerative cell therapy with precision genomic medicine --- spanning patient cell acquisition, gene editing and cellular reprogramming, and preclinical testing for safety, efficacy, and function --- to extend the existing clinical paradigm to familial Parkinson's disease patients. With its genetically defined target population and application of novel, precise genome editing and cellular reprogramming techniques to generate individualized cell products, this work will be well-aligned with the aims of precision and genomic medicine. Futhermore, this project has the potential to inform and refine existing cell replacement therapy approaches not only in Parkinson's disease but in disease broadly. 

\

_Proposed mentors_

I propose to conduct this work under the mentorship of Dr. Bin Song, a member of the T32 Training Program faculty in Precision and Genomic Medicine and the Research Director of the George A. "Doc" Lopez, MD, Laboratory for Regenerative Cell Therapy in the Department of Neurosurgery at Massachusetts General Hospital. Dr. Jeffrey Schweitzer, the Clinical Director of the Lopez Lab, will serve as an ongoing collaborator. Together, Drs. Song and Schweitzer led the first reported autologous cell replacement therapy for Parkinson's disease (Schweitzer, Song, et al., _New England Journal of Medicine_, 2020) #text(fill: red)[[Schweitzer]], and the lab is currently supporting a clinical trial for its use in sporadic Parkinson's disease (under NCT06687837). With their support, I am confident that I will be able to complete this work to advance a truly personalized therapy for familial Parkinson's disease while continuing my growth toward becoming an independent investigator in precision medicine.

