#import "style.typ": project
#show: project

= Project objective and criteria:

#pagebreak()

= L444P primers:
These primers amplify a 300 bp amplicon via high-throughput sequencing.

Forward (5'-3'): #text(font: "DejaVu Sans Mono")[GCATGGCTCCAGGCCTAGAG] \
Reverse (5'-3'): #text(font: "DejaVu Sans Mono")[CAACGCTGTCTTCAGCCCAC]

_GBA1_: \
#text(font: "DejaVu Sans Mono")[GCATGGCTCCAGGCCTAGAGAGCCAGGGCAGAGCCTCTGCAGGAGTTATG \ GGGTGGGTCCGTGGGTGGGTGACTTCTTAGATGAGGGTTTCATGGGAGGT \ 
ACCCCGAGGGACTCTGACCATCTGTTCCCACATTCAGCAAGTTCATTCCT \ 
GAGGGCTCCCAGAGAGTGGGGCTGGTTGCCAGTCAGAAGAACGACCTGGA \ 
CGCAGTGGCACTGATGCATCCCGATGGCTCTGCTGTTGTGGTCGTGCTAA \ 
ACCGGTGAGGGCAATGGTGAGGTCTGGGAAGTGGGCTGAAGACAGCGTTG]

_GBAP1_: \
#text(font: "DejaVu Sans Mono")[
GCATGGCTCCAGGCCTAGAGAGCCAGGGCAGAGCCTTTGCAGGAGTTATG \ 
GGGTGGGTCCGTGGGTGGGCGACTTCTTAGATGAGGGTTTCATGGGAGGT \ 
ACCCCGAGGGACTCTGACCATCTGTTCCCACATTCAGCAAGTTCATTCCT \ 
GAGGGCTCCCAGAGAGTGGGGCTGGTTGCCAGTCAGAAGAACGACCCGGA \ 
CGCAGTGGCACTGATGCATCCCGATGGCTCTGCTGTTGTGGTCGTGCTAA \ 
ACCGGTGAGGGCAATGGTGAGGTCTGGGAAGTGGGCTGAAGACAGCGTTG
]